version: '2'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=scrobblecast
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
     - "5432:5432"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "2m"
        # max-file: "2"

