# Bumped to 2.2 - for init support
version: '2.2'

services:
  scrape:
    # container_name: scrape
    build: .
    init: true # Tini forwards signals and reaps processes
    environment:
      - HOSTALIAS # no value inherits from ENV, which is set in Makefile
      - NATSURL=nats://nats.ts.imetrical.com:4222
      - DB_DIALECT=sqlite
    # command: npm start
    ports:
      - "8000:8000"

    volumes:
      - ./credentials.json:/usr/src/app/credentials.json:ro
      - ./credentials.loggly.json:/usr/src/app/credentials.loggly.json:ro
      # bind mount on linux: uid(node)==uid(daniel)==1000: lucky, now that container runs as node user
      - ./data:/usr/src/app/data

    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "2m"
        # max-file: "2"


