language: node_js

# test on multiple node.js versions
node_js:
  - 9.5

before_install: cd js

install:
  - npm install

script:
  - npm test

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
#notifications:
#  irc: "irc.freenode.org#travis"
