version: 2
jobs:
  build:
    working_directory: ~/daneroo/scrobbleCast
    parallelism: 1
    docker:
    # node:18 not yet available
      - image: circleci/node:16
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "js/package-lock.json" }}
      - run:
          working_directory: ~/daneroo/scrobbleCast/js
          name: npm-install
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "js/package-lock.json" }}
          paths:
            - ./js/node_modules
      - run:
          working_directory: ~/daneroo/scrobbleCast/js
          name: test
          command: npm test
