version: "2.1"
orbs:
  node: circleci/node@5.0.3

jobs:
  build:
    working_directory: ~/daneroo/scrobbleCast
    parallelism: 1
    docker:
      - image: "cimg/base:stable"

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "js/pnpm-lock.yaml" }}
      - node/install:
          node-version: "18"
      - run:
          name: Install pnpm
          # pnpm version should match the GitHub action pnpm version and be pinned
          command: corepack enable && corepack prepare pnpm@8
      - run:
          working_directory: ~/daneroo/scrobbleCast/js
          name: Install dependencies
          command: pnpm install --frozen-lockfile --loglevel error
      - save_cache:
          key: dependency-cache-{{ checksum "js/pnpm-lock.yaml" }}
          paths:
            - ./js/node_modules
      - run:
          working_directory: ~/daneroo/scrobbleCast/js
          name: test
          command: pnpm test
