version: 2
jobs:
  build:
    working_directory: ~/daneroo/scrobbleCast
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          working_directory: ~/daneroo/scrobbleCast
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          working_directory: ~/daneroo/scrobbleCast
          name: npm-install
          command: npm install
      - save_cache:
          working_directory: ~/daneroo/scrobbleCast
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          working_directory: ~/daneroo/scrobbleCast
          name: test
          command: npm test
