# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# TODO: define the image tagging process and it's relation to branch/tag events

name: Scrape-CI

on:
  push
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: js # this will become `scrape`

    strategy:
      matrix:
        # What we actually want is: current active, and lts
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          # pnpm version should match the CircleCI pnpm version and be pinned
          version: 8 # required

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm" # comment out for local `act` run
          cache-dependency-path: ./js/pnpm-lock.yaml

      - name: Report versions
        run: |
          echo "node: $(node --version)"
          echo "pnpm: $(pnpm --version)"

      - name: install dependencies
        # --frozen-lockfile should already be default on CI
        run: pnpm install --frozen-lockfile --loglevel error

      - name: Test
        run: pnpm test

  # https://github.com/marketplace/actions/publish-docker
  #  i.e. https://github.com/elgohr/Publish-Docker-Github-Action
  container:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish to Registry
        # if: ${{ github.event_name != 'pull_request' }}
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: daneroo/scrobblecast/scrape
          workdir: js
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          snapshot: true # add a tag like: 2021091401115446b3b3
          tag_names: true # includes refs (branch and tags)
          # tags: "latest,${{ env.STATE_RELEASE_VERSION }}"
          # disables push for local `act` run || or pull requests
          # no_push: ${{ github.event_name != 'pull_request' }}
